---
# Source: parent-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myrelease-parent-chart
  labels:
    helm.sh/chart: parent-chart-0.1.0
    app.kubernetes.io/name: parent-chart
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: parent-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myrelease-parent-chart
  labels:
    helm.sh/chart: parent-chart-0.1.0
    app.kubernetes.io/name: parent-chart
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: parent-chart
    app.kubernetes.io/instance: myrelease
---
# Source: parent-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrelease-parent-chart
  labels:
    helm.sh/chart: parent-chart-0.1.0
    app.kubernetes.io/name: parent-chart
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: parent-chart
      app.kubernetes.io/instance: myrelease
  template:
    metadata:
      labels:
        helm.sh/chart: parent-chart-0.1.0
        app.kubernetes.io/name: parent-chart
        app.kubernetes.io/instance: myrelease
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: myrelease-parent-chart
      containers:
        - name: parent-chart
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: parent-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "myrelease-parent-chart-test-connection"
  labels:
    helm.sh/chart: parent-chart-0.1.0
    app.kubernetes.io/name: parent-chart
    app.kubernetes.io/instance: myrelease
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['myrelease-parent-chart:80']
  restartPolicy: Never
